SELECT COLAB.NOME AS COLAB_NOME, DEP.NOME AS NOME_DEP, DEP.DATA_NASCIMENTO
FROM BRH.COLABORADOR COLAB
JOIN BRH.DEPENDENTE DEP
ON COLAB.MATRICULA = DEP.COLABORADOR
WHERE TO_CHAR(DEP.DATA_NASCIMENTO, 'MM')IN(04, 05, 06) or UPPER(DEP.NOME) LIKE '%H%'
ORDER BY COLAB.NOME, DEP.NOME

~~~~~~~~~~

SELECT COLAB.NOME, COLAB.SALARIO
FROM BRH.COLABORADOR COLAB
WHERE COLAB.SALARIO = 
(SELECT MAX (BRH.COLABORADOR.SALARIO)FROM BRH.COLABORADOR) 
ORDER BY COLAB.SALARIO DESC

~~~~~~~~~~

SELECT COLAB.MATRICULA, COLAB.NOME, COLAB.SALARIO,
(CASE WHEN COLAB.SALARIO <= 3000.00 THEN 'Júnior'
WHEN COLAB.SALARIO >=3000.01 
AND COLAB.SALARIO <= 6000.00  THEN 'Pleno'
WHEN COLAB.SALARIO >=6000.01 
AND COLAB.SALARIO <= 20000.00 THEN 'Sênior'
ELSE 'Corpo diretor'
END)AS SENIORIDADE
FROM BRH.COLABORADOR COLAB
ORDER BY SENIORIDADE, COLAB.NOME

~~~~~~~~~~

SELECT DEP.NOME AS DEPARTAMENTO, PROJ.NOME AS PROJETO, COUNT (*)AS NUMERO_COLAB
FROM BRH.DEPARTAMENTO DEP
INNER JOIN BRH.COLABORADOR COLAB 
ON DEP.SIGLA = COLAB.DEPARTAMENTO
INNER JOIN BRH.ATRIBUICAO ATT
ON COLAB.MATRICULA = ATT.COLABORADOR
INNER JOIN BRH.PROJETO PROJ
ON ATT.PROJETO = PROJ.ID
GROUP BY DEP.NOME,PROJ.NOME
ORDER BY DEP.NOME, PROJ.NOME
  
~~~~~~~~~~

SELECT COLAB.NOME,COUNT (*)AS DEPENDENTES
FROM BRH.DEPENDENTE DEP
INNER JOIN BRH.COLABORADOR COLAB
ON DEP.COLABORADOR = COLAB.MATRICULA
GROUP BY COLAB.NOME 
HAVING COUNT (*) >= 2
ORDER BY COLAB.NOME, DEPENDENTES DESC

~~~~~~~~~~

SELECT CPF,nome,data_nascimento,parentesco,colaborador,floor((SYSDATE - BRH.DEPENDENTE.DATA_NASCIMENTO)/365.0) AS IDADE, 
(CASE WHEN (SYSDATE - BRH.DEPENDENTE.DATA_NASCIMENTO)/365 < 18 THEN 'Menor de Idade'
ELSE 'Maior de Idade'
END)AS Faixa_Etaria
FROM BRH.DEPENDENTE
ORDER BY COLABORADOR,NOME

~~~~~~~~~~
CREATE OR REPLACE VIEW BRH.VW_DEP AS
SELECT CPF,nome as nome_dep,data_nascimento,parentesco,colaborador, floor((SYSDATE - BRH.DEPENDENTE.DATA_NASCIMENTO)/365.0) AS IDADE, 
(CASE WHEN (SYSDATE - BRH.DEPENDENTE.DATA_NASCIMENTO)/365 < 18 THEN 'Menor de Idade'
ELSE 'Maior de Idade'
END)AS Faixa_Etaria
FROM BRH.DEPENDENTE
ORDER BY COLABORADOR,NOME

~~~~~~~~~~

SELECT COLABORADOR, SUM(VALOR) AS TOTAL FROM (
SELECT D.COLABORADOR,100 AS VALOR
FROM BRH.VW_DEP D
WHERE D.PARENTESCO = 'Cônjuge'
UNION
SELECT D.COLABORADOR, 50 AS VALOR
FROM BRH.VW_DEP D
WHERE D.PARENTESCO = 'Filho(a)' AND D.FAIXA_ETARIA = 'Maior de Idade'
UNION ALL
SELECT D.COLABORADOR, 25 AS VALOR
FROM BRH.VW_DEP D
WHERE D.PARENTESCO = 'Filho(a)' AND D.FAIXA_ETARIA = 'Menor de Idade'
UNION ALL
SELECT COLAB.MATRICULA,
CASE
WHEN COLAB.SALARIO <3000 THEN COLAB.SALARIO * 0.01
WHEN COLAB.SALARIO <=6000 THEN COLAB.SALARIO * 0.02
WHEN COLAB.SALARIO <=20000 THEN COLAB.SALARIO * 0.03
ELSE COLAB.SALARIO * 0.05
END  
AS VALOR
FROM BRH.COLABORADOR COLAB
)
GROUP BY COLABORADOR
ORDER BY COLABORADOR

~~~~~~~~~~

SELECT * 
FROM (
SELECT ROWNUM AS NUMERO, COLAB.NOME
FROM  BRH.COLABORADOR COLAB
)PG
WHERE ROWNUM <11
ORDER BY NOME ;


SELECT * 
FROM (
SELECT ROWNUM AS NUMERO, COLAB.NOME
FROM  BRH.COLABORADOR COLAB
)PG
WHERE NUMERO > 10 AND NUMERO <= 20 
ORDER BY NOME ;


SELECT * 
FROM (
SELECT ROWNUM AS NUMERO, COLAB.NOME
FROM  BRH.COLABORADOR COLAB
)PG
WHERE NUMERO > 20 AND NUMERO <= 30 
ORDER BY NOME ;

~~~~~~~~~~

SELECT ATRIB.COLABORADOR, COUNT(ATRIB.PROJETO) AS PROJETOS
FROM BRH.ATRIBUICAO ATRIB
GROUP BY ATRIB.COLABORADOR
HAVING COUNT(ATRIB.PROJETO) = (SELECT COUNT(*) FROM BRH.PROJETO);