SELECT SIGLA, NOME FROM DEPARTAMENTO
ORDER BY NOME

~~~~~~~~~~~~~~~~~~~~

SELECT COLABORADOR.NOME AS COLAB_NOME,DEPENDENTE.NOME AS DEP_NOME,DEPENDENTE.DATA_NASCIMENTO,DEPENDENTE.PARENTESCO FROM DEPENDENTE, COLABORADOR	
WHERE DEPENDENTE.COLABORADOR = COLABORADOR.MATRICULA
ORDER BY COLAB_NOME, DEP_NOME

~~~~~~~~~~~~~~~~~~~~

INSERT INTO COLABORADOR 
VALUES
("AA123","375.558.785-12","Fulano de Tal","fulanodetal@email.com","fulanodetal@corp.com","100000.00",
"DIR","71222-100","SOBRADO 8")

INSERT INTO PROJETO
VALUES 
(5,"BI","Z123","2023/08/23","2024/04/23")

INSERT INTO TELEFONE_COLABORADOR
VALUES
("(61) 9 9999-9999","AA123","M")

INSERT INTO PAPEL
VALUES 
("8","Especialista de Negócios")

INSERT INTO ATRIBUICAO
VALUES
("AA123","5","8")

~~~~~~~~~~~~~~~~~~~~

DELETE FROM ATRIBUICAO
 WHERE COLABORADOR IN ('H123', 'M123', 'R123', 'W123');
  
DELETE FROM TELEFONE_COLABORADOR 
 WHERE COLABORADOR IN  ('H123', 'M123', 'R123', 'W123');
  
DELETE FROM DEPENDENTE
 WHERE COLABORADOR IN ('H123', 'M123', 'R123', 'W123');

UPDATE DEPARTAMENTO
   SET CHEFE = 'F123'
 WHERE SIGLA = 'SECAP';
 
DELETE FROM COLABORADOR
 WHERE DEPARTAMENTO = 'SECAP';
 
DELETE FROM DEPARTAMENTO
 WHERE SIGLA = 'SECAP';