SELECT SIGLA, NOME FROM BRH.DEPARTAMENTO
ORDER BY NOME

~~~~~~~~~~

SELECT BRH.COLABORADOR.NOME AS COLAB_NOME,BRH.DEPENDENTE.NOME AS DEP_NOME,BRH.DEPENDENTE.DATA_NASCIMENTO,BRH.DEPENDENTE.PARENTESCO FROM BRH.DEPENDENTE, BRH.COLABORADOR	
WHERE DEPENDENTE.COLABORADOR = COLABORADOR.MATRICULA
ORDER BY COLAB_NOME, DEP_NOME

~~~~~~~~~~

INSERT INTO BRH.COLABORADOR 
(MATRICULA, CPF, NOME, EMAIL_PESSOAL, EMAIL_CORPORATIVO, SALARIO, DEPARTAMENTO, CEP, COMPLEMENTO_ENDERECO)
VALUES
('AA123','375.558.785-12','Fulano de Tal','fulanodetal@email.com','fulanodetal@corp.com',90000.00,
'DIR','71222-100','SOBRADO 8')

INSERT INTO BRH.PROJETO
(ID, NOME, RESPONSAVEL, INICIO, FIM)
VALUES 
(10,'BI','Z123','24/08/2022','24/04/2024')

INSERT INTO BRH.TELEFONE_COLABORADOR
(NUMERO, COLABORADOR, TIPO)
VALUES
('(61)9 9999-9999','AA123','M')

INSERT INTO BRH.PAPEL
(ID, NOME)
VALUES 
('8','Especialista de Negócios')

INSERT INTO BRH.ATRIBUICAO
VALUES
('AA123','10','8')

~~~~~~~~~~

DELETE FROM BRH.ATRIBUICAO
 WHERE COLABORADOR IN ('H123', 'M123', 'R123', 'W123');
  
DELETE FROM BRH.TELEFONE_COLABORADOR 
 WHERE COLABORADOR IN  ('H123', 'M123', 'R123', 'W123');
  
DELETE FROM BRH.DEPENDENTE
 WHERE COLABORADOR IN ('H123', 'M123', 'R123', 'W123');

UPDATE BRH.DEPARTAMENTO
   SET CHEFE = 'F123'
 WHERE SIGLA = 'SECAP';
 
DELETE FROM BRH.COLABORADOR
 WHERE DEPARTAMENTO = 'SECAP';
 
DELETE FROM BRH.DEPARTAMENTO
 WHERE SIGLA = 'SECAP';
 
 ~~~~~~~~~~
 
SELECT BRH.COLABORADOR.NOME,BRH.COLABORADOR.EMAIL_CORPORATIVO, BRH.TELEFONE_COLABORADOR.NUMERO
FROM BRH.TELEFONE_COLABORADOR , BRH.COLABORADOR
WHERE MATRICULA = COLABORADOR AND TIPO = 'M'

~~~~~~~~~~

SELECT D.NOME NOME_DEPARTAMENTO,
       CHEFE.NOME CHEFE,
       ALOCACAO.NOME,
       PROJ.NOME PROJETO,
       PAP.NOME FUNCAO,
       TELC.NUMERO TELEFONE, 
       DEP.NOME DEPENDENTE
  FROM BRH.DEPARTAMENTO D
 INNER JOIN BRH.COLABORADOR CHEFE
    ON D.CHEFE = CHEFE.MATRICULA
 INNER JOIN BRH.COLABORADOR ALOCACAO 
    ON D.SIGLA = ALOCACAO.DEPARTAMENTO
 INNER JOIN BRH.TELEFONE_COLABORADOR TELC
    ON TELC.COLABORADOR = ALOCACAO.MATRICULA
  LEFT JOIN BRH.DEPENDENTE DEP
    ON DEP.COLABORADOR = ALOCACAO.MATRICULA
    LEFT JOIN BRH.ATRIBUICAO ATRI
    ON ATRI.COLABORADOR = ALOCACAO.MATRICULA
    INNER JOIN BRH.PAPEL PAP
    ON PAP.ID = ATRI.PAPEL
    INNER JOIN BRH.PROJETO PROJ
    ON PROJ.ID = ATRI.PROJETO

    
    
 ORDER BY D.NOME, ALOCACAO.NOME;